<?php

/**
 * @file
 * Functions to support theming in the GG theme.
 */

/**
 * Implements hook_preprocess_page().
 */
function gg_preprocess_page(&$variables) {
  // Add front page specific library.
  if ($variables['is_front']) {
    $variables['#attached']['library'][] = 'gg/front-page';
  }
}

/**
 * Implements hook_preprocess_node().
 */
function gg_preprocess_node(&$variables) {
  // Add custom variables or processing here.
}

